title: Whitby's Jekyll website
author: Harry Whitby
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Whitby's website and blog.

# social links
github_username:  h-whitby

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
